name: Publish Stable Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          PROMPTRUN_BASE_URL: ${{ secrets.PROMPTRUN_BASE_URL }}

      - name: Build package
        run: npm run build
        env:
          PROMPTRUN_BASE_URL: ${{ secrets.PROMPTRUN_BASE_URL }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Version and Publish
        run: |
          # Check if there are any changesets
          if [ -z "$(ls -A .changeset 2>/dev/null | grep -v 'README.md\|config.json')" ]; then
            echo "No changesets found. Skipping release."
            exit 0
          fi

          # Version the packages
          npx changeset version

          # Publish to NPM
          npx changeset publish

          # Create and push git tags
          git push --follow-tags origin main
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROMPTRUN_BASE_URL: ${{ secrets.PROMPTRUN_BASE_URL }}
